### ISSUE TITLE
Error Msg: Could not load requested bundle.

### ISSUE THREAD

**Issue by ranjanmanish95** [cortezaproject/corteza-server-corredor#16]
@darh @tjerman I have uploaded my extension onto the corredor container and deployed but the corredor logs are showing me error: could not load requested bundle.
![Screenshot (43)](https://user-images.githubusercontent.com/33874102/113134386-58c70e00-923e-11eb-98f6-bec3a9d2b6b2.png)
 version is 2020.6.
Also, I am preety confused about bundling of client scripts as it is mentioned in the document. We have to upload the bundled script inside each application folder like compose or just need to add the webpack dependency in package.json file.
Please help me on this.

**Comment by tjerman** [comment]
@ranjanmanish95

Note that I will be referring to the documentation of the latest 2021.3 release. Corredor related things remain mostly the same but the documentation is quite better.

Client scripts need to be bundled in order for them to work properly with modules and such.
Corredor automatically creates bundles based on the (let's call it) "bundle directory" defined by the [file structure](https://docs.cortezaproject.org/corteza-docs/2021.3/integrator-guide/automation-scripts/index.html#_file_structure).
As an example, if you wish to use an automation script inside Compose, you would place your scripts under the `client-scripts/compose` directory -- this creates a `compose.client-scripts.js` bundle.

In regards to the error message. If you look closely, you will see that it is trying to request the `admin.client-scripts.js` bundle (automation scripts dedicated for the admin web app). Since our built-in ext. nor (I'm assuming) your ext. does not define any client scripts for the admin web app there is no bundle available (the web app requests the bundle automatically).
It's a little lame how we show this error, but it's not not ok.

**Comment by ranjanmanish95** [comment]
@Tomaž Jerman
Thanks for reaching out and guidance. This will help me a lot while
bundling the extensions.
Also just one query is that i want to write an automation script to fetch
and save the data into corteza using an already available api endpoint and
Compose API. So for that which scripts should i use?? (sink scripts or
normal server side).
And if i use sink scripts then do i have to add http configuration of the
server and corredor inside .env file??
Your guidance is much appreciated.
Thanks and regards
Manish Ranjan

**Comment by tjerman** [comment]
@ranjanmanish95 

**Sink scripts** should be used when you wish to use Corteza "as a webhook"; when a request comes into a sink route, a corresponding automation script/workflow is triggered.
**"Regular scripts"** should be used when some operation should be invoked from Corteza, such as send an email when a record is created.

The above is not 100% true (sink scripts can also be invoked from Corteza, and "regular scripts" can be invoked from outside), but is close enough to help you better imagine it.

For your case, you define a regular script with a manual (explicit) trigger that would use a library like Axios to fetch the data from the external API.
The response can then be processed and saved to Corteza using Corredor helpers.

> And if i use sink scripts then do i have to add http configuration of the
> server and corredor inside .env file??

I am unsure what exactly you mean by this. How you configure your scripts to know what endpoint to use is completely up to you. You can define a separate .env (or similar config) file inside your extension that defines the endpoints. You can also have the endpoints baked in or provided via a Settings module (like we have done for the CRM and ServiceSolution extensions).

___

I will close the issue here; If there is anything else regarding the original issue feel free to reopen it.
If there are other things, feel free to open new issues/reach out on our forum.
